export enum MetricTypeEnum {
  GREETING_ACTIVITY_REPORT = "GREETING_ACTIVITY_REPORT",
  FACT_FINDING_ACTIVITY_REPORT = "FACT_FINDING_ACTIVITY_REPORT",
  STRIKING_ACTIVITY_REPORT = "STRIKING_ACTIVITY_REPORT",
  SUCCESSFULL_GREETING = "SUCCESSFULL_GREETING",
  SUCCESSFULL_FACT_FINDING = "SUCCESSFULL_FACT_FINDING",
  APPROVED_CLOSING_REQUEST = "APPROVED_CLOSING_REQUEST",
}
