export enum SalesPerformanceMetricTypeEnum {
    SALES_ACTIVITY_REPORT = 'SALES_ACTIVITY_REPORT',
    APPROVED_CLOSING_REQUEST_SUM = 'APPROVED_CLOSING_REQUEST_SUM',
    APPROVED_CLOSING_REQUEST_COUNT = 'APPROVED_CLOSING_REQUEST_COUNT',
}