export enum SalesPerformanceMetricTypeEnum {
  GREETING_ACTIVITY_REPORT_COUNT = "GREETING_ACTIVITY_REPORT_COUNT",
  FACT_FINDING_ACTIVITY_REPORT_COUNT = "FACT_FINDING_ACTIVITY_REPORT_COUNT",
  STRIKING_ACTIVITY_REPORT_COUNT = "STRIKING_ACTIVITY_REPORT_COUNT",
  SUCCESSFULL_GREETING_COUNT = "SUCCESSFULL_GREETING_COUNT",
  SUCCESSFULL_FACT_FINDING_COUNT = "SUCCESSFULL_FACT_FINDING_COUNT",
  APPROVED_CLOSING_REQUEST_SUM = "APPROVED_CLOSING_REQUEST_SUM",
  APPROVED_CLOSING_REQUEST_COUNT = "APPROVED_CLOSING_REQUEST_COUNT",
}
